week40/todo/loginapp/urls.py
from django.urls import path

from . import views


app_name = 'loginapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('password_reset', views.password_reset, name='password_reset'),
]

week40/todo/todoapp/urls.py
from django.urls import path

from . import views


app_name = 'todoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>', views.details, name='details'),
]

week40/todo/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
    path('todo/', include('todoapp.urls', namespace='todoapp')),
    path('admin/', admin.site.urls),
]

week40/todo/loginapp/models.py
from django.db import models

# Create your models here.

week40/todo/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User


class TodoItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    status = models.BooleanField()
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.pk}:{self.title}, by {self.user}"

week40/todo/loginapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout

from .utils import random_string


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request, 
            username=request.POST['user'], 
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            # is this just stupid? context = {'user':request.POST['user']}
            return HttpResponseRedirect(reverse('todoapp:index'))
        else:
            #context = {'error':'Username or password is wrong.'}
            context['error'] = 'Username or password is wrong.'

    return render(request, 'loginapp/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))


def signup(request):
    if User.is_authenticated:
        dj_logout(request)
    context = {}
    if request.method == 'POST':
        if not request.POST['password'] == request.POST['repeatpassword']:
            context['error'] = 'Passwords do not match.'
            return render(request, 'loginapp/signup.html', context)
        if len(User.objects.filter(username=request.POST['user'])) > 0:
            context['error'] = 'Username already exists.'
            return render(request, 'loginapp/signup.html', context)
        user = User.objects.create_user(request.POST['user'],password=request.POST['password'])
        user.save()
        dj_login(request, user)
        return HttpResponseRedirect(reverse('todoapp:index'))

    return render(request, 'loginapp/signup.html')



def password_reset(request):
    context = {}
    if request.method == 'POST':
        users = User.objects.filter(username=request.POST['user'])
        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))
        else:
            context['error'] = 'No such username.'
        
    return render(request, 'loginapp/password_reset.html', context)

week40/todo/todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse

from .models import *


@login_required
def index(request):
    if request.method == 'GET':
        todo_items = TodoItem.objects.filter(user=request.user)
        context = {
            'todos': todo_items
        }
        return render(request, 'todoapp/index.html', context)

    if request.method == 'POST':
        todo_item = TodoItem()
        todo_item.title = request.POST['title']
        todo_item.description = request.POST['description']
        todo_item.status = False
        todo_item.user = request.user
        todo_item.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()


@login_required
def details(request, pk):
    todo = get_object_or_404(TodoItem, pk=pk, user=request.user)

    if request.method == 'GET':
        context = {
            'todo': todo
        }
        return render(request, 'todoapp/details.html', context)

    if request.method == 'POST':
        todo.title = request.POST['title']
        todo.description = request.POST['description']
        status = request.POST.getlist('status')
        if len(status) > 0:
            todo.status = True
        else:
            todo.status = False
        todo.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()

week40/todo/loginapp/templates/loginapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    {{user}}
    <form action="." method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <label for="password">Password</label>
        <br />
        <input type="password" id="password" name="password" placeholder="Password">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
        <p><a href="{% url 'loginapp:password_reset' %}">Reset your password</a></p>
    {% endif  %}
    <hr>
    <a href="{% url 'loginapp:signup' %}">Sign up</a>
</body>
</html>

week40/todo/loginapp/templates/loginapp/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password Reset</title>
</head>
<body>
    <h1>Password Reset</h1>
    {{user}}
    <form action="{% url 'loginapp:password_reset'  %}" method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}
    <hr>
</body>
</html>

week40/todo/loginapp/templates/loginapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign-up</title>
</head>
<body>
    <h1>Sign-up</h1>
    <hr>
    <form action="{% url 'loginapp:signup' %}" method="POST">
            {% csrf_token %}
            <label for="user">Username</label>
            <br />
            <input type="text" id="user" name="user" placeholder="User Name">
            <br />
            <label for="password">Password</label>
            <br />
            <input type="password" id="password" name="password" placeholder="Password">
            <br />
            <label for="repeatpassword">Repeat Password</label>
            <br />
            <input type="password" id="repeatpassword" name="repeatpassword" placeholder="Repeat Password">
            <br />
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

week40/todo/todoapp/templates/todoapp/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Details</title>
</head>
<body>
    <h1>Details</h1>
    {{ todo.user }}
    <hr>
    <form action="{% url 'todoapp:details' todo.pk %}" method="post">
        {% csrf_token  %}
        <label for="title">Title</label>
        <br />
        <input type="text" name="title" id="title" value="{{ todo.title  }}">
        <br />
        <label for="description">Description</label>
        <br />
        <textarea name="description" id="description">{{ todo.description }}</textarea>
        <br />
        <label for="status">Status</label>
        <input type="checkbox" name="status" id="status" {% if todo.status %}checked{% endif %}>
        <br />
        <button>Submit</button>
    </form>
</body>
</html>

week40/todo/todoapp/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todoapp</title>
</head>
<body>
    <h1>Todo app!</h1>
    <hr>
    <a href="{% url 'loginapp:logout' %}">Log out</a>
    <hr>
    <ul>
        {% for todo in todos  %}
            <li>
                <a href="{% url 'todoapp:details' todo.pk  %}">
                    {{ todo.title }}
                </a>
            </li>
        {% endfor  %}
    </ul>
    <hr>
    <form action="." method="post">
        {% csrf_token  %}
        <label for="title">Title</label>
        <br />
        <input type="text" name="title" id="title">
        <br />
        <label for="description">Description</label>
        <br />
        <textarea name="description" id="description">{{ todo.description }}</textarea>
        <br />
        <button>Submit</button>
    </form>
</body>
</html>